### ISSUE TITLE
Cannot set api key / get response from chatgpt

### ISSUE THREAD

**Issue by ben-wall** [skyfireitdiy/chatgpt#1]
Chatgpt never responds with any output so I tried adding my api key like this

" call chatgpt#SetKeyFile("/home/myuser/.openaikey")

this fails with:

121: Undefined variable: keyfile

changing the filename to .openai.key and removing the call in init.vim (using neovim) also does not work

**Comment by skyfireitdiy** [comment]
Thank you for reporting the issue. We apologize for not noticing it earlier due to a heavy workload. The problem has now been fixed, and we have added a few new feature. Please feel free to try it again, and thank you for your patience.
